site_name: 'LibCrowds Documentation'
theme:
  name: 'material'
repo_name: 'LibCrowds/libcrowds'
repo_url: 'https://github.com/LibCrowds/libcrowds'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/LibCrowds'
    - type: 'twitter'
      link: 'https://twitter.com/LibCrowds'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
pages:
  - Introduction: 'index.md'
  - Setup:
    - Getting Started: 'setup/index.md'
    - Configuring PYBOSSA: 'setup/configuring-pybossa.md'
    - Configuring LibCrowds: 'setup/configuring-libcrowds.md'
    - Deployment: 'setup/deployment.md'
    - Testing: 'setup/testing.md'
  - Administration:
    - Collection Microsites:
      - New Collection: 'admin/collection/new.md'
      - Open Collection: 'admin/collection/open.md'
      - Core Settings: 'admin/collection/settings.md'
      - Page Content: 'admin/collection/content.md'
      - Celebration: 'admin/collection/celebration.md'
      - Featured Projects: 'admin/collection/featured.md'
      - Task Presenter: 'admin/collection/presenter.md'
      - Tags: 'admin/collection/tags.md'
      - Project Templates: 'admin/collection/templates.md'
      - Terminology: 'admin/collection/terminology.md'
      - Volumes: 'admin/collection/volumes.md'
      - Delete: 'admin/collection/delete.md'
    - Projects:
      - New Project: 'admin/project/new.md'
      - Open Project: 'admin/project/open.md'
      - Core Settings: 'admin/project/settings.md'
      - Thumbnail: 'admin/project/thumbnail.md'
      - Tags: 'admin/project/tags.md'
      - Collection: 'admin/project/collection.md'
      - Help: 'admin/project/help.md'
      - Volumes: 'admin/project/volumes.md'
    - Site:
      - Dashboard: 'admin/site/dashboard.md'
      - Announcements: 'admin/site/announcements.md'
      - Background Jobs: 'admin/site/jobs.md'
      - User Management: 'admin/site/users.md'
  - FAQ: 'glossary.md'
  - Glossary: 'glossary.md'
