site_name: 'LibCrowds Documentation'
theme:
  name: 'material'
repo_name: 'LibCrowds/libcrowds'
repo_url: 'https://github.com/LibCrowds/libcrowds'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/LibCrowds'
    - type: 'twitter'
      link: 'https://twitter.com/LibCrowds'
    - type: 'envelope'
      link: 'mailto:digitalresearch@bl.uk'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.superfences
google_analytics:
  - 'UA-59584422-5'
  - 'auto'
pages:
  - Introduction: 'index.md'
  - Setup:
    - Introduction: 'setup/introduction.md'
    - Installation: 'setup/installation.md'
    - Configuring PYBOSSA: 'setup/configuring-pybossa.md'
    - Configuring LibCrowds: 'setup/configuring-libcrowds.md'
    - Deployment: 'setup/deployment.md'
    - Testing: 'setup/testing.md'
  - Projects:
    - Introduction: 'projects/introduction.md'
    - New Project: 'projects/new.md'
    - Settings:
      - Core Details: 'projects/details.md'
      - Thumbnail: 'projects/thumbnail.md'
      - Tags: 'projects/tags.md'
      - Collection: 'projects/collection.md'
      - Help: 'projects/help.md'
      - Volume: 'projects/volume.md'
      - Results: 'projects/results.md'
  - Templates:
    - Introduction: 'templates/introduction.md'
    - Core Details: 'templates/details.md'
    - Analysis Rules: 'templates/analysis.md'
    - New Template: 'templates/new.md'
  - Collection Admin:
    - Introduction: 'collections/introduction.md'
    - New Collection: 'collections/new.md'
    - Settings:
      - Core Details: 'collections/details.md'
      - Page Content: 'collections/content.md'
      - Celebration: 'collections/celebration.md'
      - Featured Projects: 'collections/featured.md'
      - Task Presenter: 'collections/presenter.md'
      - Tags: 'collections/tags.md'
      - Volumes: 'collections/volumes.md'
      - Delete: 'collections/delete.md'
  - Site Admin:
    - Dashboard: 'site/dashboard.md'
    - Announcements: 'site/announcements.md'
    - Background Jobs: 'site/jobs.md'
    - User Management: 'site/users.md'
  - Results Analysis: 'analysis.md'
  - Data:
    - Introduction: 'data/introduction.md'
    - Web Annotations: 'data/annotations.md'
    - Downloads: 'data/downloads.md'
  - FAQ: 'FAQ.md'
  - Glossary: 'glossary.md'
