site_name: 'LibCrowds Documentation'
theme:
  name: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/LibCrowds/docs'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/LibCrowds'
    - type: 'twitter'
      link: 'https://twitter.com/LibCrowds'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
pages:
  - Introduction: 'index.md'
  - Setup:
    - Installation: 'setup/installation.md'
    - Configuring PYBOSSA: 'setup/configuring-pybossa.md'
    - Configuring LibCrowds: 'setup/configuring-libcrowds.md'
    - Deployment: 'setup/deployment.md'
    - Testing: 'setup/testing.md'
  - Projects:
    - Getting Started: 'projects/getting-started.md'
    - New Project: 'projects/new.md'
    - Open Project: 'projects/open.md'
    - Core Settings: 'projects/settings.md'
    - Thumbnail: 'projects/thumbnail.md'
    - Tags: 'projects/tags.md'
    - Collection: 'projects/collection.md'
    - Help: 'projects/help.md'
    - Volumes: 'projects/volumes.md'
  - Collection Microsites:
    - Getting Started: 'collections/getting-started.md'
    - New Collection: 'collections/new.md'
    - Open Collection: 'collections/open.md'
    - Core Settings: 'collections/settings.md'
    - Page Content: 'collections/content.md'
    - Celebration: 'collections/celebration.md'
    - Featured Projects: 'collections/featured.md'
    - Task Presenter: 'collections/presenter.md'
    - Tags: 'collections/tags.md'
    - Project Templates: 'collections/templates.md'
    - Terminology: 'collections/terminology.md'
    - Volumes: 'collections/volumes.md'
    - Delete: 'collections/delete.md'
  - Site:
    - Dashboard: 'site/dashboard.md'
    - Announcements: 'site/announcements.md'
    - Background Jobs: 'site/jobs.md'
    - User Management: 'site/users.md'
  - FAQ: 'FAQ.md'
  - Glossary: 'glossary.md'
