site_name: 'LibCrowds Documentation'
theme:
  name: 'material'
repo_name: 'LibCrowds/libcrowds'
repo_url: 'https://github.com/LibCrowds/libcrowds'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/LibCrowds'
    - type: 'twitter'
      link: 'https://twitter.com/LibCrowds'
    - type: 'envelope'
      link: 'mailto:digitalresearch@bl.uk'
extra_css:
  - assets/style/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.superfences
google_analytics:
  - 'UA-59584422-5'
  - 'auto'
pages:
  - Introduction: 'index.md'
  - Setup:
    - Introduction: 'setup/introduction.md'
    - Local Installation: 'setup/installation.md'
    - Deployment: 'setup/deployment.md'
    - Plugins: 'setup/plugins.md'
    - Configuring PYBOSSA: 'setup/configuring-pybossa.md'
    - Configuring LibCrowds: 'setup/configuring-libcrowds.md'
    - Testing: 'setup/testing.md'
  - Projects:
    - Introduction: 'projects/introduction.md'
    - New Project: 'projects/new.md'
    - Tags: 'projects/tags.md'
    - Thumbnail: 'projects/thumbnail.md'
    - Results: 'projects/results.md'
    - Delete: 'projects/delete.md'
    - Core Details: 'projects/details.md'
    - Collection: 'projects/collection.md'
    - Volume: 'projects/volume.md'
    - Template: 'projects/template.md'
    - Webhooks: 'projects/webhooks.md'
  - Templates:
    - Introduction: 'templates/introduction.md'
    - New Template: 'templates/new.md'
    - Core Details: 'templates/details.md'
    - Task: 'templates/task.md'
    - Redundancy: 'templates/redundancy.md'
    - Parent: 'templates/parent.md'
    - Analysis: 'templates/analysis.md'
    - Tutorial: 'templates/tutorial.md'
    - Delete: 'templates/delete.md'
  - Collection Admin:
    - Introduction: 'collections/introduction.md'
    - New Collection: 'collections/new.md'
    - Core Details: 'collections/details.md'
    - Page Content: 'collections/content.md'
    - Celebrations: 'collections/celebrations.md'
    - Tags: 'collections/tags.md'
    - Volumes: 'collections/volumes.md'
    - Exports: 'collections/exports.md'
    - Featured Projects: 'collections/featured.md'
    - Task Presenter: 'collections/presenter.md'
    - Delete: 'collections/delete.md'
  - Site Admin:
    - Dashboard: 'site/dashboard.md'
    - User Management: 'site/user-management.md'
    - Announcements: 'site/announcements.md'
    - Results: 'site/results.md'
    - Background Jobs: 'site/jobs.md'
    - Pending Templates: 'site/pending-templates.md'
  - Results Analysis: 'analysis.md'
  - Data:
    - Introduction: 'data/introduction.md'
    - Data Model: 'data/model.md'
    - Downloads: 'data/downloads.md'
  - FAQ: 'FAQ.md'
  - Glossary: 'glossary.md'
